auth_enabled: false
server:
  http_listen_port: 3100
common:
  path_prefix: /data/loki
  storage:
    s3:
      endpoint: seaweedfs:8333
      bucketnames: loki-logs
      access_key_id: ${S3_ACCESS_KEY}
      secret_access_key: ${S3_SECRET_KEY}
      s3forcepathstyle: true
  replication_factor: 1
schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: loki_index_
        period: 24h
